import { Product, Wilaya, Translation, Language } from './types';

export const BRAND_NAME = "AXIS";
export const PHONE_NUMBER_WHATSAPP = "213555123456"; 

const FALLBACK_IMGS = {
  bodysuit: "https://images.unsplash.com/photo-1595341888016-a392ef81b7de?q=80&w=1000&auto=format&fit=crop", 
  knee: "https://images.unsplash.com/photo-1552674605-5d28c475e6c6?q=80&w=1000&auto=format&fit=crop",
  spine: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?q=80&w=1000&auto=format&fit=crop",
  insoles: "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?q=80&w=1000&auto=format&fit=crop",
  neck: "https://images.unsplash.com/photo-1579126038374-6064e9370f0f?q=80&w=1000&auto=format&fit=crop"
};

export const TRANSLATIONS: Record<Language, Translation> = {
  fr: {
    navShop: "ARSENAL",
    navAbout: "VISION",
    heroTitle: "BÂTISSEZ\nVOTRE HÉRITAGE.",
    heroSubtitle: "Ne laissez pas la gravité écraser votre structure. Redressez-vous. Dominez. Équipements de correction anatomique de haute précision.",
    heroCta: "REJOINDRE L'ÉLITE",
    certified: "INGÉNIERIE AXIS",
    edition: "SÉRIE GEN-1",
    stat1: "50,000+",
    stat1Label: "CORPS TRANSFORMÉS",
    stat2: "98.4%",
    stat2Label: "TAUX DE RÉUSSITE",
    stat3: "58",
    stat3Label: "ZONES COUVERTES",
    problemTitle: "EFFONDREMENT STRUCTUREL",
    problemText: "La sédentarité est un poison lent. Votre dos se voûte. Vos articulations s'usent prématurément. Votre présence s'efface. C'est inacceptable.",
    problem1: "DÉGRADATION PHYSIQUE",
    problem2: "PERTE DE PUISSANCE",
    productsTitle: "L'ARSENAL",
    productsSubtitle: "QUANTITÉ LIMITÉE / LOT 04",
    addToCart: "SÉLECTIONNER",
    buyNow: "ACQUÉRIR",
    viewProduct: "ANALYSER",
    techTitle: "ARCHITECTURE CORPORELLE",
    techSub: "MATÉRIAUX DE POINTE",
    tech1Title: "COMPRESSION THERMIQUE",
    tech1Desc: "Active la circulation sanguine et prépare le muscle à l'effort.",
    tech2Title: "STRUCTURE À MÉMOIRE",
    tech2Desc: "Polymère flexible qui force l'alignement naturel sans contrainte.",
    tech3Title: "ABSORPTION D'IMPACT",
    tech3Desc: "Gel matriciel dissipant 40% de l'énergie cinétique à chaque pas.",
    tech4Title: "DESIGN ANATOMIQUE",
    tech4Desc: "Moulé sur des athlètes d'élite pour une fusion totale avec le corps.",
    reviewsTitle: "RAPPORTS DE TERRAIN",
    review1: "Une transformation radicale. Ma posture impose le respect dès que j'entre dans une pièce. AXIS n'est pas un accessoire, c'est une nécessité.",
    review2: "Après 12h debout, mes jambes sont fraîches. C'est comme avoir une nouvelle paire de jambes chaque matin.",
    review3: "La douleur au cou a disparu en 3 jours. Je peux enfin me concentrer sur mes objectifs.",
    verifiedClient: "MEMBRE VÉRIFIÉ",
    shipping: "EXPÉDITION EXPRESS",
    whyUsTitle1: "LIVRAISON NATIONALE",
    whyUsDesc1: "58 Wilayas couvertes.",
    whyUsTitle2: "DESIGN FURTIF",
    whyUsDesc2: "Invisible et puissant.",
    whyUsTitle3: "GARANTIE TOTALE",
    whyUsDesc3: "Satisfait ou remboursé.",
    secureCheckout: "COMMANDE SÉCURISÉE",
    orderSummary: "VOTRE SÉLECTION",
    identity: "IDENTITÉ",
    contact: "LIGNE DIRECTE",
    zone: "WILAYA",
    sector: "ADRESSE EXACTE",
    confirmOrder: "VALIDER L'ACQUISITION",
    orderBumpTitle: "KIT DE MAINTENANCE (+1500 DA)",
    orderBumpDesc: "Prolongez la durée de vie de votre équipement.",
    paymentNotice: "PAIEMENT À LA LIVRAISON • AUCUN RISQUE",
    loading: "PRÉPARATION...",
    ticker: "LIVRAISON OFFERTE DÈS 8000 DA /// RETOUR GRATUIT /// SUPPORT 24/7",
    back: "RETOUR",
    details: "DÉTAILS TECHNIQUES",
    selectLoadout: "SÉLECTIONNEZ VOTRE MODÈLE",
    finalCtaTitle: "N'ATTENDEZ PAS LE DÉCLIN",
    finalCtaSub: "PRENEZ LE CONTRÔLE"
  },
  en: {
    navShop: "ARSENAL",
    navAbout: "VISION",
    heroTitle: "BUILD YOUR\nLEGACY.",
    heroSubtitle: "Don't let gravity crush your structure. Stand tall. Dominate. High-precision anatomical correction gear.",
    heroCta: "JOIN THE ELITE",
    certified: "AXIS ENGINEERING",
    edition: "GEN-1 SERIES",
    stat1: "50,000+",
    stat1Label: "BODIES TRANSFORMED",
    stat2: "98.4%",
    stat2Label: "SUCCESS RATE",
    stat3: "58",
    stat3Label: "ZONES DEPLOYED",
    problemTitle: "STRUCTURAL COLLAPSE",
    problemText: "Sedentary life is a slow poison. Your back hunches. Your joints wear out prematurely. Your presence fades. This is unacceptable.",
    problem1: "PHYSICAL DECAY",
    problem2: "POWER LOSS",
    productsTitle: "THE ARSENAL",
    productsSubtitle: "LIMITED BATCH / 04",
    addToCart: "SELECT",
    buyNow: "ACQUIRE",
    viewProduct: "ANALYZE",
    techTitle: "BODY ARCHITECTURE",
    techSub: "ADVANCED MATERIALS",
    tech1Title: "THERMAL COMPRESSION",
    tech1Desc: "Activates blood flow and primes muscles for action.",
    tech2Title: "MEMORY STRUCTURE",
    tech2Desc: "Flexible polymer forces natural alignment without restriction.",
    tech3Title: "IMPACT ABSORPTION",
    tech3Desc: "Matrix gel dissipates 40% of kinetic energy with every step.",
    tech4Title: "ANATOMICAL DESIGN",
    tech4Desc: "Molded on elite athletes for total fusion with the body.",
    reviewsTitle: "FIELD REPORTS",
    review1: "Radical transformation. My posture commands respect the moment I walk into a room. AXIS is not an accessory, it's a necessity.",
    review2: "After 12 hours standing, my legs feel fresh. It's like having a new pair of legs every morning.",
    review3: "Neck pain vanished in 3 days. I can finally focus on my goals.",
    verifiedClient: "VERIFIED MEMBER",
    shipping: "EXPRESS SHIPPING",
    whyUsTitle1: "NATIONWIDE DELIVERY",
    whyUsDesc1: "All 58 Wilayas.",
    whyUsTitle2: "STEALTH DESIGN",
    whyUsDesc2: "Invisible power.",
    whyUsTitle3: "TOTAL WARRANTY",
    whyUsDesc3: "Satisfaction guaranteed.",
    secureCheckout: "SECURE ORDER",
    orderSummary: "YOUR SELECTION",
    identity: "IDENTITY",
    contact: "DIRECT LINE",
    zone: "REGION",
    sector: "EXACT ADDRESS",
    confirmOrder: "CONFIRM ACQUISITION",
    orderBumpTitle: "MAINTENANCE KIT (+1500 DA)",
    orderBumpDesc: "Extend the lifespan of your gear.",
    paymentNotice: "PAYMENT ON DELIVERY • ZERO RISK",
    loading: "PREPARING...",
    ticker: "FREE SHIPPING OVER 8000 DA /// FREE RETURNS /// 24/7 SUPPORT",
    back: "BACK",
    details: "TECHNICAL SPECS",
    selectLoadout: "SELECT YOUR MODEL",
    finalCtaTitle: "DON'T WAIT FOR DECLINE",
    finalCtaSub: "TAKE CONTROL"
  },
  ar: {
    navShop: "الترسانة",
    navAbout: "الرؤية",
    heroTitle: "اصنع\nهيبتك.",
    heroSubtitle: "لا تدع الجاذبية تحطم قامتك. قف بشموخ. وسيطر. معدات تصحيح تشريحية عالية الدقة للنخبة.",
    heroCta: "انضم للنخبة",
    certified: "هندسة AXIS",
    edition: "الإصدار الأول GEN-1",
    stat1: "+50,000",
    stat1Label: "جسم تم تحويله",
    stat2: "%98.4",
    stat2Label: "نسبة نجاح",
    stat3: "58",
    stat3Label: "ولاية مغطاة",
    problemTitle: "الانهيار الهيكلي",
    problemText: "نمط الحياة الخامل سم بطيء. ظهرك ينحني. مفاصلك تتآكل قبل الأوان. وهيبتك تتلاشى. هذا أمر مرفوض.",
    problem1: "التدهور الجسدي",
    problem2: "فقدان القوة",
    productsTitle: "الترسانة",
    productsSubtitle: "كمية محدودة / الدفعة 04",
    addToCart: "اختيار",
    buyNow: "امتلك الآن",
    viewProduct: "تحليل المنتج",
    techTitle: "هندسة الجسد",
    techSub: "مواد متطورة",
    tech1Title: "الضغط الحراري",
    tech1Desc: "ينشط الدورة الدموية ويهيئ العضلات للأداء العالي.",
    tech2Title: "هيكل بذاكرة",
    tech2Desc: "بوليمر مرن يفرض الاستقامة الطبيعية دون تقييد الحركة.",
    tech3Title: "امتصاص الصدمات",
    tech3Desc: "جل متطور يشتت 40% من الطاقة الحركية مع كل خطوة.",
    tech4Title: "تصميم تشريحي",
    tech4Desc: "مصمم بناءً على مقاييس رياضيين عالميين للاندماج التام مع الجسم.",
    reviewsTitle: "تقارير الميدان",
    review1: "تحول جذري. وقفتي تفرض الاحترام فور دخولي أي مكان. AXIS ليس مجرد إكسسوار، إنه ضرورة.",
    review2: "بعد 12 ساعة من الوقوف، ساقاي تشعران بالنشاط. كأنني أملك ساقين جديدتين كل صباح.",
    review3: "اختفى ألم الرقبة في 3 أيام. أخيراً يمكنني التركيز على أهدافي.",
    verifiedClient: "عضو موثق",
    shipping: "شحن سريع",
    whyUsTitle1: "توصيل وطني",
    whyUsDesc1: "تغطية شاملة لـ 58 ولاية.",
    whyUsTitle2: "تصميم خفي",
    whyUsDesc2: "قوة غير مرئية.",
    whyUsTitle3: "ضمان شامل",
    whyUsDesc3: "استرداد كامل للمبلغ.",
    secureCheckout: "طلب آمن",
    orderSummary: "مختاراتك",
    identity: "الهوية",
    contact: "رقم الهاتف",
    zone: "الولاية",
    sector: "العنوان الدقيق",
    confirmOrder: "تأكيد الامتلاك",
    orderBumpTitle: "طقم العناية الكاملة (+1500 دج)",
    orderBumpDesc: "للحفاظ على كفاءة معداتك لأطول فترة.",
    paymentNotice: "الدفع عند الاستلام • بدون مخاطرة",
    loading: "جاري التجهيز...",
    ticker: "شحن مجاني فوق 8000 دج /// إرجاع مجاني /// دعم متواصل 24/7",
    back: "عودة",
    details: "المواصفات التقنية",
    selectLoadout: "اختر نسختك",
    finalCtaTitle: "لا تنتظر الانهيار",
    finalCtaSub: "استعد السيطرة"
  }
};

export const getProducts = (lang: Language): Product[] => {
  const isAr = lang === 'ar';
  
  return [
    {
      id: "bodysuit",
      name: "SCULPT-X1",
      tagline: isAr ? "نحت الجسم الكامل" : "FULL BODY SCULPT",
      price: 5900,
      oldPrice: 8500,
      shortDesc: isAr ? "يخفي العيوب فوراً ويعيد رسم القوام." : "Efface les imperfections instantanément. Redéfinit la silhouette.",
      description: isAr 
        ? "درعك اليومي ضد الترهل. قماش ضاغط متطور يعمل كبشرة ثانية، يشد البطن، يرفع الصدر، وينحت الخصر في لحظة ارتدائه. ثقة مطلقة تحت أي ملابس."
        : "Votre armure quotidienne contre le relâchement. Textile compressif avancé agissant comme une seconde peau : gaine le ventre, remonte le buste et sculpte la taille dès l'enfilage. Confiance absolue sous n'importe quelle tenue.",
      image: "bodysuit.jpg",
      gallery: [FALLBACK_IMGS.bodysuit],
      features: [
        { title: isAr ? "شد فوري" : "INSTANT LIFT", desc: isAr ? "نتيجة مرئية في ثوان" : "Résultat visible en secondes." },
        { title: isAr ? "إخفاء تام" : "INVISIBLE", desc: isAr ? "لا يظهر تحت الملابس" : "Indétectable sous les vêtements." }
      ],
      specs: ["Microfibre 4-Way", "Sans Coutures", "Anti-Transpirant"],
      painPoint: "Forme",
      solution: "Sculpt",
      benefit: "Impact"
    },
    {
      id: "neck",
      name: "NECK-ZERO",
      tagline: isAr ? "تحرير الفقرات العنقية" : "CERVICAL RELEASE",
      price: 3200,
      oldPrice: 5000,
      shortDesc: isAr ? "يزيل ضغط الرقبة والصداع في دقائق." : "Élimine la pression cervicale et les maux de tête en quelques minutes.",
      description: isAr 
        ? "الجهاز النهائي لمن يقضون ساعات أمام الشاشات. تقنية السحب الهوائي تباعد بين الفقرات بلطف، مما يزيل الضغط عن الأعصاب ويعيد تدفق الدم للرأس. وداعاً للصداع."
        : "L'outil ultime pour ceux qui vivent devant un écran. La traction pneumatique écarte doucement les vertèbres, libérant les nerfs comprimés et rétablissant le flux sanguin vers le cerveau. Adieu les migraines.",
      image: "neck.jpg",
      gallery: [FALLBACK_IMGS.neck],
      features: [
        { title: isAr ? "سحب هوائي" : "TRACTION AIR", desc: isAr ? "تخفيف الضغط العصبي" : "Décompression nerveuse." },
        { title: isAr ? "راحة فورية" : "INSTANT RELIEF", desc: isAr ? "استرخاء عضلات الرقبة" : "Relâchement musculaire." }
      ],
      specs: ["Velours Premium", "Pompe Manuelle", "3 Niveaux"],
      painPoint: "Cou",
      solution: "Traction",
      benefit: "Libération"
    },
    {
      id: "knee",
      name: "KINETIC GUARD",
      tagline: isAr ? "تدعيم المفاصل التكتيكي" : "TACTICAL JOINT SUPPORT",
      price: 2900,
      oldPrice: 4200,
      shortDesc: isAr ? "حول ركبتك إلى حصن منيع." : "Transformez votre genou en forteresse.",
      description: isAr 
        ? "الألم يجعلك ضعيفاً. هذه الدعامة توفر ثباتاً ميكانيكياً وحرارياً للركبة، مما يسمح لك بالحركة، الجري، والعمل دون خوف من الإصابة أو الألم."
        : "La douleur vous affaiblit. Cette genouillère offre une stabilité mécanique et thermique, vous permettant de bouger, courir et travailler sans la peur de la blessure ou de la douleur.",
      image: "genouillere.jpg",
      gallery: [FALLBACK_IMGS.knee],
      features: [
        { title: isAr ? "تثبيت كامل" : "LOCKDOWN", desc: isAr ? "أشرطة مانعة للانزلاق" : "Sangles anti-glisse." },
        { title: isAr ? "تنشيط حراري" : "THERMAL ACT", desc: isAr ? "تسريع الاستشفاء" : "Accélère la récupération." }
      ],
      specs: ["Néoprène 3mm", "Ressorts Latéraux", "Ajustable"],
      painPoint: "Douleur",
      solution: "Support",
      benefit: "Puissance"
    },
    {
      id: "spine",
      name: "POSTURE RIG",
      tagline: isAr ? "إعادة ضبط العمود الفقري" : "SPINE REALIGNMENT",
      price: 3500,
      oldPrice: 5500,
      shortDesc: isAr ? "افرض حضورك بقامة مستقيمة." : "Imposez votre présence avec une posture droite.",
      description: isAr 
        ? "لغة الجسد هي كل شيء. هذا الهيكل يجبر كتفيك على العودة للخلف وصدرك للأمام. يعيد برمجة عضلات ظهرك لتقف بشموخ وتتنفس بعمق. استعد هيبتك."
        : "Le langage corporel est tout. Ce rig force vos épaules vers l'arrière et votre torse vers l'avant. Il reprogramme vos muscles dorsaux pour vous tenir droit et respirer profondément. Réclamez votre espace.",
      image: "correcteur.jpg",
      gallery: [FALLBACK_IMGS.spine],
      features: [
        { title: isAr ? "تصحيح المسار" : "CORRECTION", desc: isAr ? "استقامة فورية" : "Alignement immédiat." },
        { title: isAr ? "ذاكرة عضلية" : "MUSCLE MEMORY", desc: isAr ? "نتائج دائمة" : "Résultats permanents." }
      ],
      specs: ["Structure Rigide", "Respirant", "Unisexe"],
      painPoint: "Dos",
      solution: "Alignement",
      benefit: "Dominance"
    },
    {
      id: "insoles",
      name: "GRAVITY SOLES",
      tagline: isAr ? "نظام تعليق للقدمين" : "FOOT SUSPENSION SYSTEM",
      price: 2500,
      oldPrice: 3800,
      shortDesc: isAr ? "امشِ فوق أي سطح دون تعب." : "Marchez sur n'importe quelle surface sans fatigue.",
      description: isAr 
        ? "ترقية ضرورية لأي حذاء. طبقة الجل الهندسية تمتص صدمات الارتطام بالأرض، تحمي ركبتيك وعمودك الفقري من الاهتزازات. طاقة لا تنتهي طوال اليوم."
        : "Upgrade essentiel pour toute chaussure. La couche de gel ingénierie absorbe les chocs d'impact, protégeant vos genoux et votre colonne des vibrations. Une énergie inépuisable toute la journée.",
      image: "semelles.jpg",
      gallery: [FALLBACK_IMGS.insoles],
      features: [
        { title: isAr ? "امتصاص الصدمات" : "SHOCK ABSORB", desc: isAr ? "حماية المفاصل" : "Protection articulaire." },
        { title: isAr ? "راحة قصوى" : "MAX COMFORT", desc: isAr ? "للاستخدام اليومي" : "Usage intensif." }
      ],
      specs: ["Gel Silice", "Découpe Facile", "Hygiénique"],
      painPoint: "Pieds",
      solution: "Amorti",
      benefit: "Endurance"
    }
  ];
};

export const WILAYAS: Wilaya[] = [
  { code: "01", name: "Adrar", arName: "أدرار" }, { code: "02", name: "Chlef", arName: "الشلف" }, { code: "03", name: "Laghouat", arName: "الأغواط" },
  { code: "04", name: "Oum El Bouaghi", arName: "أم البواقي" }, { code: "05", name: "Batna", arName: "باتنة" }, { code: "06", name: "Béjaïa", arName: "بجاية" },
  { code: "07", name: "Biskra", arName: "بسكرة" }, { code: "08", name: "Béchar", arName: "بشار" }, { code: "09", name: "Blida", arName: "البليدة" },
  { code: "10", name: "Bouira", arName: "البويرة" }, { code: "11", name: "Tamanrasset", arName: "تمنراست" }, { code: "12", name: "Tébessa", arName: "تبسة" },
  { code: "13", name: "Tlemcen", arName: "تلمسان" }, { code: "14", name: "Tiaret", arName: "تيارت" }, { code: "15", name: "Tizi Ouzou", arName: "تيزي وزو" },
  { code: "16", name: "Alger", arName: "الجزائر" }, { code: "17", name: "Djelfa", arName: "الجلفة" }, { code: "18", name: "Jijel", arName: "جيجل" },
  { code: "19", name: "Sétif", arName: "سطيف" }, { code: "20", name: "Saïda", arName: "سعيدة" }, { code: "21", name: "Skikda", arName: "سكيكدة" },
  { code: "22", name: "Sidi Bel Abbès", arName: "سيدي بلعباس" }, { code: "23", name: "Annaba", arName: "عنابة" }, { code: "24", name: "Guelma", arName: "قالمة" },
  { code: "25", name: "Constantine", arName: "قسنطينة" }, { code: "26", name: "Médéa", arName: "المدية" }, { code: "27", name: "Mostaganem", arName: "مستغانم" },
  { code: "28", name: "M'Sila", arName: "المسيلة" }, { code: "29", name: "Mascara", arName: "معسكر" }, { code: "30", name: "Ouargla", arName: "ورقلة" },
  { code: "31", name: "Oran", arName: "وهران" }, { code: "32", name: "El Bayadh", arName: "البيض" }, { code: "33", name: "Illizi", arName: "إليزي" },
  { code: "34", name: "Bordj Bou Arreridj", arName: "برج بوعريريج" }, { code: "35", name: "Boumerdès", arName: "بومرداس" }, { code: "36", name: "El Tarf", arName: "الطرف" },
  { code: "37", name: "Tindouf", arName: "تندوف" }, { code: "38", name: "Tissemsilt", arName: "تيسمسيلت" }, { code: "39", name: "El Oued", arName: "الوادي" },
  { code: "40", name: "Khenchela", arName: "خنشلة" }, { code: "41", name: "Souk Ahras", arName: "سوق أهراس" }, { code: "42", name: "Tipaza", arName: "تيبازة" },
  { code: "43", name: "Mila", arName: "ميلة" }, { code: "44", name: "Aïn Defla", arName: "عين الدفلى" }, { code: "45", name: "Naâma", arName: "النعامة" },
  { code: "46", name: "Aïn Témouchent", arName: "عين تموشنت" }, { code: "47", name: "Ghardaïa", arName: "غرداية" }, { code: "48", name: "Relizane", arName: "غليزان" },
  { code: "49", name: "Timimoun", arName: "تيميمون" }, { code: "50", name: "Bordj Badji Mokhtar", arName: "برج باجي مختار" }, { code: "51", name: "Ouled Djellal", arName: "أولاد جلال" },
  { code: "52", name: "Béni Abbès", arName: "بني عباس" }, { code: "53", name: "In Salah", arName: "عين صالح" }, { code: "54", name: "In Guezzam", arName: "عين قزام" },
  { code: "55", name: "Touggourt", arName: "تقرت" }, { code: "56", name: "Djanet", arName: "جانت" }, { code: "57", name: "El M'Ghair", arName: "المغير" },
  { code: "58", name: "El Meniaa", arName: "المنيعة" }
];

export const FAKE_SALES_DATA = [
  { name: "Sonia M.", city: "Hydra", product: "SCULPT-X1" },
  { name: "Amira K.", city: "Oran", product: "GRAVITY SOLES" },
  { name: "Farida B.", city: "Sétif", product: "POSTURE RIG" },
  { name: "Nassim Z.", city: "Constantine", product: "KINETIC GUARD" },
  { name: "Yasmine D.", city: "Alger", product: "NECK-ZERO" },
  { name: "Karim L.", city: "Annaba", product: "SCULPT-X1" },
  { name: "Leila H.", city: "Tlemcen", product: "NECK-ZERO" },
];